// GENERATED by scripts/gen-db-types.mjs — do not edit by hand.
// Regenerate: npm run test:db -- --setup-only && npm run db:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      app_settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          is_public: boolean;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          is_public?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          description?: string | null;
          is_public?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "app_settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      application_status_history: {
        Row: {
          id: number;
          application_id: string;
          from_status: Database["public"]["Enums"]["application_status"] | null;
          to_status: Database["public"]["Enums"]["application_status"];
          changed_by: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: never;
          application_id: string;
          from_status?: Database["public"]["Enums"]["application_status"] | null;
          to_status: Database["public"]["Enums"]["application_status"];
          changed_by?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: never;
          application_id?: string;
          from_status?: Database["public"]["Enums"]["application_status"] | null;
          to_status?: Database["public"]["Enums"]["application_status"];
          changed_by?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "application_status_history_application_id_fkey";
            columns: ["application_id"];
            isOneToOne: false;
            referencedRelation: "applications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "application_status_history_changed_by_fkey";
            columns: ["changed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      applications: {
        Row: {
          id: string;
          vacancy_id: string;
          candidate_id: string;
          cover_letter: string | null;
          status: Database["public"]["Enums"]["application_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vacancy_id: string;
          candidate_id: string;
          cover_letter?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vacancy_id?: string;
          candidate_id?: string;
          cover_letter?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "applications_candidate_id_fkey";
            columns: ["candidate_id"];
            isOneToOne: false;
            referencedRelation: "candidate_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "applications_vacancy_id_fkey";
            columns: ["vacancy_id"];
            isOneToOne: false;
            referencedRelation: "vacancies";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: number;
          actor_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          data: Json;
          ip: string | null;
          created_at: string;
        };
        Insert: {
          id?: never;
          actor_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          data?: Json;
          ip?: string | null;
          created_at?: string;
        };
        Update: {
          id?: never;
          actor_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          data?: Json;
          ip?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      candidate_certificates: {
        Row: {
          id: string;
          candidate_id: string;
          name: string;
          issuer: string | null;
          issued_at: string | null;
          file_path: string | null;
          is_verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          name: string;
          issuer?: string | null;
          issued_at?: string | null;
          file_path?: string | null;
          is_verified?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          name?: string;
          issuer?: string | null;
          issued_at?: string | null;
          file_path?: string | null;
          is_verified?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "candidate_certificates_candidate_id_fkey";
            columns: ["candidate_id"];
            isOneToOne: false;
            referencedRelation: "candidate_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      candidate_education: {
        Row: {
          id: string;
          candidate_id: string;
          institution: string;
          level: Database["public"]["Enums"]["education_level"];
          field: string | null;
          start_year: number | null;
          end_year: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          institution: string;
          level?: Database["public"]["Enums"]["education_level"];
          field?: string | null;
          start_year?: number | null;
          end_year?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          institution?: string;
          level?: Database["public"]["Enums"]["education_level"];
          field?: string | null;
          start_year?: number | null;
          end_year?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "candidate_education_candidate_id_fkey";
            columns: ["candidate_id"];
            isOneToOne: false;
            referencedRelation: "candidate_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      candidate_experience: {
        Row: {
          id: string;
          candidate_id: string;
          company_name: string;
          position: string;
          location_text: string | null;
          start_date: string;
          end_date: string | null;
          is_current: boolean;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          company_name: string;
          position: string;
          location_text?: string | null;
          start_date: string;
          end_date?: string | null;
          is_current?: boolean;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          company_name?: string;
          position?: string;
          location_text?: string | null;
          start_date?: string;
          end_date?: string | null;
          is_current?: boolean;
          description?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "candidate_experience_candidate_id_fkey";
            columns: ["candidate_id"];
            isOneToOne: false;
            referencedRelation: "candidate_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      candidate_portfolio: {
        Row: {
          id: string;
          candidate_id: string;
          title: string;
          description: string | null;
          url: string | null;
          image_path: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          candidate_id: string;
          title: string;
          description?: string | null;
          url?: string | null;
          image_path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          candidate_id?: string;
          title?: string;
          description?: string | null;
          url?: string | null;
          image_path?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "candidate_portfolio_candidate_id_fkey";
            columns: ["candidate_id"];
            isOneToOne: false;
            referencedRelation: "candidate_profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      candidate_profiles: {
        Row: {
          id: string;
          headline: string;
          about: string | null;
          profession_id: number | null;
          experience_years: number;
          education_level: Database["public"]["Enums"]["education_level"] | null;
          expected_salary_min: number | null;
          expected_salary_max: number | null;
          salary_type: Database["public"]["Enums"]["salary_type"];
          employment_types: Database["public"]["Enums"]["employment_type"][];
          availability: Database["public"]["Enums"]["availability_status"];
          available_from: string | null;
          has_transport: boolean;
          driver_license: string[];
          remote_ok: boolean;
          relocate_ok: boolean;
          work_radius_km: number;
          region_id: number | null;
          district_id: number | null;
          settlement_id: number | null;
          mahalla_id: number | null;
          lat: number | null;
          lng: number | null;
          is_public: boolean;
          completeness: number;
          rating_avg: number;
          rating_count: number;
          completed_jobs: number;
          premium_until: string | null;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          headline?: string;
          about?: string | null;
          profession_id?: number | null;
          experience_years?: number;
          education_level?: Database["public"]["Enums"]["education_level"] | null;
          expected_salary_min?: number | null;
          expected_salary_max?: number | null;
          salary_type?: Database["public"]["Enums"]["salary_type"];
          employment_types?: Database["public"]["Enums"]["employment_type"][];
          availability?: Database["public"]["Enums"]["availability_status"];
          available_from?: string | null;
          has_transport?: boolean;
          driver_license?: string[];
          remote_ok?: boolean;
          relocate_ok?: boolean;
          work_radius_km?: number;
          region_id?: number | null;
          district_id?: number | null;
          settlement_id?: number | null;
          mahalla_id?: number | null;
          lat?: number | null;
          lng?: number | null;
          is_public?: boolean;
          completeness?: number;
          rating_avg?: number;
          rating_count?: number;
          completed_jobs?: number;
          premium_until?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          headline?: string;
          about?: string | null;
          profession_id?: number | null;
          experience_years?: number;
          education_level?: Database["public"]["Enums"]["education_level"] | null;
          expected_salary_min?: number | null;
          expected_salary_max?: number | null;
          salary_type?: Database["public"]["Enums"]["salary_type"];
          employment_types?: Database["public"]["Enums"]["employment_type"][];
          availability?: Database["public"]["Enums"]["availability_status"];
          available_from?: string | null;
          has_transport?: boolean;
          driver_license?: string[];
          remote_ok?: boolean;
          relocate_ok?: boolean;
          work_radius_km?: number;
          region_id?: number | null;
          district_id?: number | null;
          settlement_id?: number | null;
          mahalla_id?: number | null;
          lat?: number | null;
          lng?: number | null;
          is_public?: boolean;
          completeness?: number;
          rating_avg?: number;
          rating_count?: number;
          completed_jobs?: number;
          premium_until?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "candidate_profiles_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "candidate_profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "candidate_profiles_mahalla_id_fkey";
            columns: ["mahalla_id"];
            isOneToOne: false;
            referencedRelation: "mahallas";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "candidate_profiles_profession_id_fkey";
            columns: ["profession_id"];
            isOneToOne: false;
            referencedRelation: "professions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "candidate_profiles_region_id_fkey";
            columns: ["region_id"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "candidate_profiles_settlement_id_fkey";
            columns: ["settlement_id"];
            isOneToOne: false;
            referencedRelation: "settlements";
            referencedColumns: ["id"];
          },
        ];
      };
      candidate_skills: {
        Row: {
          candidate_id: string;
          skill_id: number;
          level: number;
          is_verified: boolean;
        };
        Insert: {
          candidate_id: string;
          skill_id: number;
          level?: number;
          is_verified?: boolean;
        };
        Update: {
          candidate_id?: string;
          skill_id?: number;
          level?: number;
          is_verified?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "candidate_skills_candidate_id_fkey";
            columns: ["candidate_id"];
            isOneToOne: false;
            referencedRelation: "candidate_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "candidate_skills_skill_id_fkey";
            columns: ["skill_id"];
            isOneToOne: false;
            referencedRelation: "skills";
            referencedColumns: ["id"];
          },
        ];
      };
      categories: {
        Row: {
          id: number;
          parent_id: number | null;
          slug: string;
          name_uz: string;
          name_ru: string | null;
          name_en: string | null;
          icon: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          parent_id?: number | null;
          slug: string;
          name_uz: string;
          name_ru?: string | null;
          name_en?: string | null;
          icon?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          parent_id?: number | null;
          slug?: string;
          name_uz?: string;
          name_ru?: string | null;
          name_en?: string | null;
          icon?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
        ];
      };
      companies: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          slug: string;
          company_type: Database["public"]["Enums"]["company_type"];
          stir: string | null;
          logo_url: string | null;
          description: string | null;
          website: string | null;
          region_id: number | null;
          district_id: number | null;
          settlement_id: number | null;
          mahalla_id: number | null;
          address: string | null;
          lat: number | null;
          lng: number | null;
          verification_status: Database["public"]["Enums"]["verification_status"];
          is_featured: boolean;
          featured_until: string | null;
          rating_avg: number;
          rating_count: number;
          hires_count: number;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          slug: string;
          company_type?: Database["public"]["Enums"]["company_type"];
          stir?: string | null;
          logo_url?: string | null;
          description?: string | null;
          website?: string | null;
          region_id?: number | null;
          district_id?: number | null;
          settlement_id?: number | null;
          mahalla_id?: number | null;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          verification_status?: Database["public"]["Enums"]["verification_status"];
          is_featured?: boolean;
          featured_until?: string | null;
          rating_avg?: number;
          rating_count?: number;
          hires_count?: number;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          slug?: string;
          company_type?: Database["public"]["Enums"]["company_type"];
          stir?: string | null;
          logo_url?: string | null;
          description?: string | null;
          website?: string | null;
          region_id?: number | null;
          district_id?: number | null;
          settlement_id?: number | null;
          mahalla_id?: number | null;
          address?: string | null;
          lat?: number | null;
          lng?: number | null;
          verification_status?: Database["public"]["Enums"]["verification_status"];
          is_featured?: boolean;
          featured_until?: string | null;
          rating_avg?: number;
          rating_count?: number;
          hires_count?: number;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "companies_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "companies_mahalla_id_fkey";
            columns: ["mahalla_id"];
            isOneToOne: false;
            referencedRelation: "mahallas";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "companies_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "companies_region_id_fkey";
            columns: ["region_id"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "companies_settlement_id_fkey";
            columns: ["settlement_id"];
            isOneToOne: false;
            referencedRelation: "settlements";
            referencedColumns: ["id"];
          },
        ];
      };
      company_members: {
        Row: {
          company_id: string;
          user_id: string;
          member_role: string;
          created_at: string;
        };
        Insert: {
          company_id: string;
          user_id: string;
          member_role?: string;
          created_at?: string;
        };
        Update: {
          company_id?: string;
          user_id?: string;
          member_role?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "company_members_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "company_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      complaints: {
        Row: {
          id: string;
          user_id: string;
          subject: string;
          body: string;
          status: Database["public"]["Enums"]["report_status"];
          admin_reply: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subject: string;
          body: string;
          status?: Database["public"]["Enums"]["report_status"];
          admin_reply?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subject?: string;
          body?: string;
          status?: Database["public"]["Enums"]["report_status"];
          admin_reply?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "complaints_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      conversation_participants: {
        Row: {
          conversation_id: string;
          user_id: string;
          last_read_at: string | null;
          is_blocked: boolean;
        };
        Insert: {
          conversation_id: string;
          user_id: string;
          last_read_at?: string | null;
          is_blocked?: boolean;
        };
        Update: {
          conversation_id?: string;
          user_id?: string;
          last_read_at?: string | null;
          is_blocked?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "conversation_participants_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "conversation_participants_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      conversations: {
        Row: {
          id: string;
          created_by: string | null;
          vacancy_id: string | null;
          application_id: string | null;
          last_message_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          created_by?: string | null;
          vacancy_id?: string | null;
          application_id?: string | null;
          last_message_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          created_by?: string | null;
          vacancy_id?: string | null;
          application_id?: string | null;
          last_message_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "conversations_application_id_fkey";
            columns: ["application_id"];
            isOneToOne: false;
            referencedRelation: "applications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "conversations_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "conversations_vacancy_id_fkey";
            columns: ["vacancy_id"];
            isOneToOne: false;
            referencedRelation: "vacancies";
            referencedColumns: ["id"];
          },
        ];
      };
      countries: {
        Row: {
          id: number;
          code: string;
          name_uz: string;
          name_ru: string | null;
          name_en: string | null;
        };
        Insert: {
          id?: number;
          code: string;
          name_uz: string;
          name_ru?: string | null;
          name_en?: string | null;
        };
        Update: {
          id?: number;
          code?: string;
          name_uz?: string;
          name_ru?: string | null;
          name_en?: string | null;
        };
        Relationships: [
        ];
      };
      districts: {
        Row: {
          id: number;
          region_id: number;
          slug: string;
          kind: Database["public"]["Enums"]["district_kind"];
          name_uz: string;
          name_ru: string | null;
          name_en: string | null;
          soato_code: string | null;
          lat: number | null;
          lng: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          region_id: number;
          slug: string;
          kind?: Database["public"]["Enums"]["district_kind"];
          name_uz: string;
          name_ru?: string | null;
          name_en?: string | null;
          soato_code?: string | null;
          lat?: number | null;
          lng?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          region_id?: number;
          slug?: string;
          kind?: Database["public"]["Enums"]["district_kind"];
          name_uz?: string;
          name_ru?: string | null;
          name_en?: string | null;
          soato_code?: string | null;
          lat?: number | null;
          lng?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "districts_region_id_fkey";
            columns: ["region_id"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["id"];
          },
        ];
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          vacancy_id: string | null;
          candidate_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          vacancy_id?: string | null;
          candidate_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          vacancy_id?: string | null;
          candidate_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "favorites_candidate_id_fkey";
            columns: ["candidate_id"];
            isOneToOne: false;
            referencedRelation: "candidate_profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "favorites_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "favorites_vacancy_id_fkey";
            columns: ["vacancy_id"];
            isOneToOne: false;
            referencedRelation: "vacancies";
            referencedColumns: ["id"];
          },
        ];
      };
      mahallas: {
        Row: {
          id: number;
          district_id: number;
          settlement_id: number | null;
          slug: string;
          name_uz: string;
          name_ru: string | null;
          name_en: string | null;
          code: string | null;
          lat: number | null;
          lng: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          district_id: number;
          settlement_id?: number | null;
          slug: string;
          name_uz: string;
          name_ru?: string | null;
          name_en?: string | null;
          code?: string | null;
          lat?: number | null;
          lng?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          district_id?: number;
          settlement_id?: number | null;
          slug?: string;
          name_uz?: string;
          name_ru?: string | null;
          name_en?: string | null;
          code?: string | null;
          lat?: number | null;
          lng?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "mahallas_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "mahallas_settlement_id_fkey";
            columns: ["settlement_id"];
            isOneToOne: false;
            referencedRelation: "settlements";
            referencedColumns: ["id"];
          },
        ];
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string | null;
          kind: Database["public"]["Enums"]["message_kind"];
          body: string | null;
          attachment_path: string | null;
          attachment_name: string | null;
          attachment_mime: string | null;
          ref_vacancy_id: string | null;
          ref_application_id: string | null;
          is_flagged: boolean;
          flag_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id?: string | null;
          kind?: Database["public"]["Enums"]["message_kind"];
          body?: string | null;
          attachment_path?: string | null;
          attachment_name?: string | null;
          attachment_mime?: string | null;
          ref_vacancy_id?: string | null;
          ref_application_id?: string | null;
          is_flagged?: boolean;
          flag_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string | null;
          kind?: Database["public"]["Enums"]["message_kind"];
          body?: string | null;
          attachment_path?: string | null;
          attachment_name?: string | null;
          attachment_mime?: string | null;
          ref_vacancy_id?: string | null;
          ref_application_id?: string | null;
          is_flagged?: boolean;
          flag_reason?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_ref_application_id_fkey";
            columns: ["ref_application_id"];
            isOneToOne: false;
            referencedRelation: "applications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_ref_vacancy_id_fkey";
            columns: ["ref_vacancy_id"];
            isOneToOne: false;
            referencedRelation: "vacancies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_sender_id_fkey";
            columns: ["sender_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: Database["public"]["Enums"]["notification_type"];
          title: string;
          body: string | null;
          link: string | null;
          data: Json;
          read_at: string | null;
          emailed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: Database["public"]["Enums"]["notification_type"];
          title: string;
          body?: string | null;
          link?: string | null;
          data?: Json;
          read_at?: string | null;
          emailed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: Database["public"]["Enums"]["notification_type"];
          title?: string;
          body?: string | null;
          link?: string | null;
          data?: Json;
          read_at?: string | null;
          emailed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      paid_services: {
        Row: {
          id: number;
          code: string;
          audience: Database["public"]["Enums"]["plan_audience"];
          name_uz: string;
          description_uz: string | null;
          price_uzs: number;
          duration_days: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          code: string;
          audience: Database["public"]["Enums"]["plan_audience"];
          name_uz: string;
          description_uz?: string | null;
          price_uzs: number;
          duration_days?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          code?: string;
          audience?: Database["public"]["Enums"]["plan_audience"];
          name_uz?: string;
          description_uz?: string | null;
          price_uzs?: number;
          duration_days?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          amount_uzs: number;
          currency: string;
          status: Database["public"]["Enums"]["payment_status"];
          provider: string;
          provider_ref: string | null;
          purpose: string;
          plan_id: number | null;
          service_id: number | null;
          target_company_id: string | null;
          target_vacancy_id: string | null;
          metadata: Json;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          amount_uzs: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payment_status"];
          provider: string;
          provider_ref?: string | null;
          purpose: string;
          plan_id?: number | null;
          service_id?: number | null;
          target_company_id?: string | null;
          target_vacancy_id?: string | null;
          metadata?: Json;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          amount_uzs?: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payment_status"];
          provider?: string;
          provider_ref?: string | null;
          purpose?: string;
          plan_id?: number | null;
          service_id?: number | null;
          target_company_id?: string | null;
          target_vacancy_id?: string | null;
          metadata?: Json;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "subscription_plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "paid_services";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_target_company_id_fkey";
            columns: ["target_company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_target_vacancy_id_fkey";
            columns: ["target_vacancy_id"];
            isOneToOne: false;
            referencedRelation: "vacancies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profession_skills: {
        Row: {
          profession_id: number;
          skill_id: number;
        };
        Insert: {
          profession_id: number;
          skill_id: number;
        };
        Update: {
          profession_id?: number;
          skill_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: "profession_skills_profession_id_fkey";
            columns: ["profession_id"];
            isOneToOne: false;
            referencedRelation: "professions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "profession_skills_skill_id_fkey";
            columns: ["skill_id"];
            isOneToOne: false;
            referencedRelation: "skills";
            referencedColumns: ["id"];
          },
        ];
      };
      professions: {
        Row: {
          id: number;
          category_id: number;
          slug: string;
          name_uz: string;
          name_ru: string | null;
          name_en: string | null;
          synonyms: string[];
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          category_id: number;
          slug: string;
          name_uz: string;
          name_ru?: string | null;
          name_en?: string | null;
          synonyms?: string[];
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          category_id?: number;
          slug?: string;
          name_uz?: string;
          name_ru?: string | null;
          name_en?: string | null;
          synonyms?: string[];
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "professions_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          phone: string | null;
          email: string | null;
          avatar_url: string | null;
          birth_year: number | null;
          gender: string | null;
          locale: string;
          phone_verified: boolean;
          identity_verified: boolean;
          certificate_verified: boolean;
          is_blocked: boolean;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          email?: string | null;
          avatar_url?: string | null;
          birth_year?: number | null;
          gender?: string | null;
          locale?: string;
          phone_verified?: boolean;
          identity_verified?: boolean;
          certificate_verified?: boolean;
          is_blocked?: boolean;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          email?: string | null;
          avatar_url?: string | null;
          birth_year?: number | null;
          gender?: string | null;
          locale?: string;
          phone_verified?: boolean;
          identity_verified?: boolean;
          certificate_verified?: boolean;
          is_blocked?: boolean;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      rate_limits: {
        Row: {
          key: string;
          hits: number;
          reset_at: string;
        };
        Insert: {
          key: string;
          hits?: number;
          reset_at: string;
        };
        Update: {
          key?: string;
          hits?: number;
          reset_at?: string;
        };
        Relationships: [
        ];
      };
      regions: {
        Row: {
          id: number;
          country_id: number;
          slug: string;
          name_uz: string;
          name_ru: string | null;
          name_en: string | null;
          soato_code: string | null;
          lat: number | null;
          lng: number | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          country_id: number;
          slug: string;
          name_uz: string;
          name_ru?: string | null;
          name_en?: string | null;
          soato_code?: string | null;
          lat?: number | null;
          lng?: number | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          country_id?: number;
          slug?: string;
          name_uz?: string;
          name_ru?: string | null;
          name_en?: string | null;
          soato_code?: string | null;
          lat?: number | null;
          lng?: number | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "regions_country_id_fkey";
            columns: ["country_id"];
            isOneToOne: false;
            referencedRelation: "countries";
            referencedColumns: ["id"];
          },
        ];
      };
      reports: {
        Row: {
          id: string;
          reporter_id: string | null;
          target_type: Database["public"]["Enums"]["report_target"];
          target_id: string;
          reason: Database["public"]["Enums"]["report_reason"];
          details: string | null;
          status: Database["public"]["Enums"]["report_status"];
          resolution_note: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reporter_id?: string | null;
          target_type: Database["public"]["Enums"]["report_target"];
          target_id: string;
          reason: Database["public"]["Enums"]["report_reason"];
          details?: string | null;
          status?: Database["public"]["Enums"]["report_status"];
          resolution_note?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          reporter_id?: string | null;
          target_type?: Database["public"]["Enums"]["report_target"];
          target_id?: string;
          reason?: Database["public"]["Enums"]["report_reason"];
          details?: string | null;
          status?: Database["public"]["Enums"]["report_status"];
          resolution_note?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reports_reporter_id_fkey";
            columns: ["reporter_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reports_resolved_by_fkey";
            columns: ["resolved_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      reviews: {
        Row: {
          id: string;
          application_id: string;
          reviewer_id: string;
          direction: string;
          reviewee_user_id: string | null;
          reviewee_company_id: string | null;
          rating: number;
          comment: string | null;
          status: Database["public"]["Enums"]["review_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          application_id: string;
          reviewer_id: string;
          direction: string;
          reviewee_user_id?: string | null;
          reviewee_company_id?: string | null;
          rating: number;
          comment?: string | null;
          status?: Database["public"]["Enums"]["review_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          application_id?: string;
          reviewer_id?: string;
          direction?: string;
          reviewee_user_id?: string | null;
          reviewee_company_id?: string | null;
          rating?: number;
          comment?: string | null;
          status?: Database["public"]["Enums"]["review_status"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_application_id_fkey";
            columns: ["application_id"];
            isOneToOne: false;
            referencedRelation: "applications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_reviewee_company_id_fkey";
            columns: ["reviewee_company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_reviewee_user_id_fkey";
            columns: ["reviewee_user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_reviewer_id_fkey";
            columns: ["reviewer_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      roles: {
        Row: {
          code: Database["public"]["Enums"]["app_role"];
          name_uz: string;
          description: string | null;
        };
        Insert: {
          code: Database["public"]["Enums"]["app_role"];
          name_uz: string;
          description?: string | null;
        };
        Update: {
          code?: Database["public"]["Enums"]["app_role"];
          name_uz?: string;
          description?: string | null;
        };
        Relationships: [
        ];
      };
      saved_searches: {
        Row: {
          id: string;
          user_id: string;
          kind: string;
          name: string;
          query: string | null;
          profession_id: number | null;
          category_id: number | null;
          region_id: number | null;
          district_id: number | null;
          settlement_id: number | null;
          radius_km: number | null;
          params: Json;
          notify: boolean;
          last_notified_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          kind: string;
          name: string;
          query?: string | null;
          profession_id?: number | null;
          category_id?: number | null;
          region_id?: number | null;
          district_id?: number | null;
          settlement_id?: number | null;
          radius_km?: number | null;
          params?: Json;
          notify?: boolean;
          last_notified_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          kind?: string;
          name?: string;
          query?: string | null;
          profession_id?: number | null;
          category_id?: number | null;
          region_id?: number | null;
          district_id?: number | null;
          settlement_id?: number | null;
          radius_km?: number | null;
          params?: Json;
          notify?: boolean;
          last_notified_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "saved_searches_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_searches_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_searches_profession_id_fkey";
            columns: ["profession_id"];
            isOneToOne: false;
            referencedRelation: "professions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_searches_region_id_fkey";
            columns: ["region_id"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_searches_settlement_id_fkey";
            columns: ["settlement_id"];
            isOneToOne: false;
            referencedRelation: "settlements";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "saved_searches_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      search_logs: {
        Row: {
          id: number;
          user_id: string | null;
          kind: string;
          query: string | null;
          profession_id: number | null;
          region_id: number | null;
          district_id: number | null;
          results_count: number | null;
          created_at: string;
        };
        Insert: {
          id?: never;
          user_id?: string | null;
          kind: string;
          query?: string | null;
          profession_id?: number | null;
          region_id?: number | null;
          district_id?: number | null;
          results_count?: number | null;
          created_at?: string;
        };
        Update: {
          id?: never;
          user_id?: string | null;
          kind?: string;
          query?: string | null;
          profession_id?: number | null;
          region_id?: number | null;
          district_id?: number | null;
          results_count?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "search_logs_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "search_logs_profession_id_fkey";
            columns: ["profession_id"];
            isOneToOne: false;
            referencedRelation: "professions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "search_logs_region_id_fkey";
            columns: ["region_id"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "search_logs_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      settlements: {
        Row: {
          id: number;
          district_id: number;
          slug: string;
          kind: Database["public"]["Enums"]["settlement_kind"];
          name_uz: string;
          name_ru: string | null;
          name_en: string | null;
          soato_code: string | null;
          lat: number | null;
          lng: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          district_id: number;
          slug: string;
          kind?: Database["public"]["Enums"]["settlement_kind"];
          name_uz: string;
          name_ru?: string | null;
          name_en?: string | null;
          soato_code?: string | null;
          lat?: number | null;
          lng?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          district_id?: number;
          slug?: string;
          kind?: Database["public"]["Enums"]["settlement_kind"];
          name_uz?: string;
          name_ru?: string | null;
          name_en?: string | null;
          soato_code?: string | null;
          lat?: number | null;
          lng?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "settlements_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
        ];
      };
      skills: {
        Row: {
          id: number;
          slug: string;
          name_uz: string;
          name_ru: string | null;
          name_en: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          slug: string;
          name_uz: string;
          name_ru?: string | null;
          name_en?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          slug?: string;
          name_uz?: string;
          name_ru?: string | null;
          name_en?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      subscription_plans: {
        Row: {
          id: number;
          code: string;
          audience: Database["public"]["Enums"]["plan_audience"];
          name_uz: string;
          description_uz: string | null;
          price_uzs: number;
          interval_months: number;
          limits: Json;
          features: Json;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: number;
          code: string;
          audience?: Database["public"]["Enums"]["plan_audience"];
          name_uz: string;
          description_uz?: string | null;
          price_uzs?: number;
          interval_months?: number;
          limits?: Json;
          features?: Json;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: number;
          code?: string;
          audience?: Database["public"]["Enums"]["plan_audience"];
          name_uz?: string;
          description_uz?: string | null;
          price_uzs?: number;
          interval_months?: number;
          limits?: Json;
          features?: Json;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          company_id: string | null;
          plan_id: number;
          status: Database["public"]["Enums"]["subscription_status"];
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_id?: string | null;
          plan_id: number;
          status?: Database["public"]["Enums"]["subscription_status"];
          current_period_start?: string;
          current_period_end: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_id?: string | null;
          plan_id?: number;
          status?: Database["public"]["Enums"]["subscription_status"];
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "subscription_plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      user_roles: {
        Row: {
          user_id: string;
          role: Database["public"]["Enums"]["app_role"];
          granted_by: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          role: Database["public"]["Enums"]["app_role"];
          granted_by?: string | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          granted_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_roles_granted_by_fkey";
            columns: ["granted_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_roles_role_fkey";
            columns: ["role"];
            isOneToOne: false;
            referencedRelation: "roles";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "user_roles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      vacancies: {
        Row: {
          id: string;
          company_id: string;
          created_by: string | null;
          title: string;
          description: string;
          category_id: number | null;
          profession_id: number | null;
          experience_min_years: number;
          education_level: Database["public"]["Enums"]["education_level"] | null;
          salary_min: number | null;
          salary_max: number | null;
          salary_currency: string;
          salary_type: Database["public"]["Enums"]["salary_type"];
          employment_type: Database["public"]["Enums"]["employment_type"];
          work_schedule: Database["public"]["Enums"]["work_schedule"];
          vacancy_tier: Database["public"]["Enums"]["vacancy_tier"];
          positions_count: number;
          region_id: number | null;
          district_id: number | null;
          settlement_id: number | null;
          mahalla_id: number | null;
          address_text: string | null;
          lat: number | null;
          lng: number | null;
          remote_allowed: boolean;
          transport_provided: boolean;
          accommodation_provided: boolean;
          meal_provided: boolean;
          urgent: boolean;
          application_deadline: string | null;
          status: Database["public"]["Enums"]["vacancy_status"];
          rejection_reason: string | null;
          is_featured: boolean;
          promoted_until: string | null;
          published_at: string | null;
          expires_at: string | null;
          views_count: number;
          applications_count: number;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          created_by?: string | null;
          title: string;
          description: string;
          category_id?: number | null;
          profession_id?: number | null;
          experience_min_years?: number;
          education_level?: Database["public"]["Enums"]["education_level"] | null;
          salary_min?: number | null;
          salary_max?: number | null;
          salary_currency?: string;
          salary_type?: Database["public"]["Enums"]["salary_type"];
          employment_type?: Database["public"]["Enums"]["employment_type"];
          work_schedule?: Database["public"]["Enums"]["work_schedule"];
          vacancy_tier?: Database["public"]["Enums"]["vacancy_tier"];
          positions_count?: number;
          region_id?: number | null;
          district_id?: number | null;
          settlement_id?: number | null;
          mahalla_id?: number | null;
          address_text?: string | null;
          lat?: number | null;
          lng?: number | null;
          remote_allowed?: boolean;
          transport_provided?: boolean;
          accommodation_provided?: boolean;
          meal_provided?: boolean;
          urgent?: boolean;
          application_deadline?: string | null;
          status?: Database["public"]["Enums"]["vacancy_status"];
          rejection_reason?: string | null;
          is_featured?: boolean;
          promoted_until?: string | null;
          published_at?: string | null;
          expires_at?: string | null;
          views_count?: number;
          applications_count?: number;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          created_by?: string | null;
          title?: string;
          description?: string;
          category_id?: number | null;
          profession_id?: number | null;
          experience_min_years?: number;
          education_level?: Database["public"]["Enums"]["education_level"] | null;
          salary_min?: number | null;
          salary_max?: number | null;
          salary_currency?: string;
          salary_type?: Database["public"]["Enums"]["salary_type"];
          employment_type?: Database["public"]["Enums"]["employment_type"];
          work_schedule?: Database["public"]["Enums"]["work_schedule"];
          vacancy_tier?: Database["public"]["Enums"]["vacancy_tier"];
          positions_count?: number;
          region_id?: number | null;
          district_id?: number | null;
          settlement_id?: number | null;
          mahalla_id?: number | null;
          address_text?: string | null;
          lat?: number | null;
          lng?: number | null;
          remote_allowed?: boolean;
          transport_provided?: boolean;
          accommodation_provided?: boolean;
          meal_provided?: boolean;
          urgent?: boolean;
          application_deadline?: string | null;
          status?: Database["public"]["Enums"]["vacancy_status"];
          rejection_reason?: string | null;
          is_featured?: boolean;
          promoted_until?: string | null;
          published_at?: string | null;
          expires_at?: string | null;
          views_count?: number;
          applications_count?: number;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "vacancies_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vacancies_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vacancies_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vacancies_district_id_fkey";
            columns: ["district_id"];
            isOneToOne: false;
            referencedRelation: "districts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vacancies_mahalla_id_fkey";
            columns: ["mahalla_id"];
            isOneToOne: false;
            referencedRelation: "mahallas";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vacancies_profession_id_fkey";
            columns: ["profession_id"];
            isOneToOne: false;
            referencedRelation: "professions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vacancies_region_id_fkey";
            columns: ["region_id"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vacancies_settlement_id_fkey";
            columns: ["settlement_id"];
            isOneToOne: false;
            referencedRelation: "settlements";
            referencedColumns: ["id"];
          },
        ];
      };
      vacancy_skills: {
        Row: {
          vacancy_id: string;
          skill_id: number;
          is_required: boolean;
        };
        Insert: {
          vacancy_id: string;
          skill_id: number;
          is_required?: boolean;
        };
        Update: {
          vacancy_id?: string;
          skill_id?: number;
          is_required?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "vacancy_skills_skill_id_fkey";
            columns: ["skill_id"];
            isOneToOne: false;
            referencedRelation: "skills";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "vacancy_skills_vacancy_id_fkey";
            columns: ["vacancy_id"];
            isOneToOne: false;
            referencedRelation: "vacancies";
            referencedColumns: ["id"];
          },
        ];
      };
      verification_requests: {
        Row: {
          id: string;
          user_id: string;
          company_id: string | null;
          type: Database["public"]["Enums"]["verification_type"];
          document_path: string | null;
          certificate_id: string | null;
          note: string | null;
          status: Database["public"]["Enums"]["request_status"];
          admin_note: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_id?: string | null;
          type: Database["public"]["Enums"]["verification_type"];
          document_path?: string | null;
          certificate_id?: string | null;
          note?: string | null;
          status?: Database["public"]["Enums"]["request_status"];
          admin_note?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_id?: string | null;
          type?: Database["public"]["Enums"]["verification_type"];
          document_path?: string | null;
          certificate_id?: string | null;
          note?: string | null;
          status?: Database["public"]["Enums"]["request_status"];
          admin_note?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "verification_requests_certificate_id_fkey";
            columns: ["certificate_id"];
            isOneToOne: false;
            referencedRelation: "candidate_certificates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "verification_requests_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "verification_requests_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "verification_requests_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      public_profiles: {
        Row: {
          id: string | null;
          first_name: string | null;
          last_name: string | null;
          avatar_url: string | null;
          phone_verified: boolean | null;
          identity_verified: boolean | null;
          certificate_verified: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          avatar_url?: string | null;
          phone_verified?: boolean | null;
          identity_verified?: boolean | null;
          certificate_verified?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          avatar_url?: string | null;
          phone_verified?: boolean | null;
          identity_verified?: boolean | null;
          certificate_verified?: boolean | null;
          created_at?: string | null;
        };
        Relationships: [
        ];
      };
    };
    Functions: {
      admin_dashboard_stats: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      application_transition_allowed: {
        Args: {
          p_from: Database["public"]["Enums"]["application_status"];
          p_to: Database["public"]["Enums"]["application_status"];
        };
        Returns: boolean;
      };
      broadcast_notification: {
        Args: {
          p_title: string;
          p_body?: string | null;
          p_link?: string | null;
          p_audience?: string | null;
        };
        Returns: number;
      };
      can_view_candidate: {
        Args: {
          p_candidate_id: string;
        };
        Returns: boolean;
      };
      can_view_candidate_private: {
        Args: {
          p_candidate_id: string;
        };
        Returns: boolean;
      };
      category_stats: {
        Args: Record<PropertyKey, never>;
        Returns: {
          id: number | null;
          slug: string | null;
          name_uz: string | null;
          icon: string | null;
          vacancy_count: number | null;
          candidate_count: number | null;
        }[];
      };
      choose_role: {
        Args: {
          p_role: Database["public"]["Enums"]["app_role"];
        };
        Returns: undefined;
      };
      company_plan_limits: {
        Args: {
          p_company_id: string;
        };
        Returns: Json;
      };
      create_notification: {
        Args: {
          p_user_id: string;
          p_type: Database["public"]["Enums"]["notification_type"];
          p_title: string;
          p_body?: string | null;
          p_link?: string | null;
          p_data?: Json | null;
        };
        Returns: string;
      };
      create_payment_intent: {
        Args: {
          p_purpose: string;
          p_code: string;
          p_provider: string;
          p_company_id?: string | null;
          p_vacancy_id?: string | null;
        };
        Returns: string;
      };
      demand_supply: {
        Args: {
          p_region_id?: number | null;
          p_limit?: number | null;
        };
        Returns: {
          region_id: number | null;
          district_id: number | null;
          district_name: string | null;
          profession_id: number | null;
          profession_name: string | null;
          vacancy_count: number | null;
          candidate_count: number | null;
          demand_ratio: number | null;
        }[];
      };
      expire_vacancies: {
        Args: Record<PropertyKey, never>;
        Returns: number;
      };
      geo_distance_km: {
        Args: {
          lat1: number;
          lng1: number;
          lat2: number;
          lng2: number;
        };
        Returns: number;
      };
      get_applicant_contact: {
        Args: {
          p_application_id: string;
        };
        Returns: {
          phone: string | null;
          email: string | null;
        }[];
      };
      get_setting: {
        Args: {
          p_key: string;
          p_default?: Json | null;
        };
        Returns: Json;
      };
      has_role: {
        Args: {
          p_role: Database["public"]["Enums"]["app_role"];
        };
        Returns: boolean;
      };
      increment_vacancy_views: {
        Args: {
          p_vacancy_id: string;
        };
        Returns: undefined;
      };
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_backend_role: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_company_member: {
        Args: {
          p_company_id: string;
        };
        Returns: boolean;
      };
      is_company_owner: {
        Args: {
          p_company_id: string;
        };
        Returns: boolean;
      };
      is_conversation_participant: {
        Args: {
          p_conversation_id: string;
        };
        Returns: boolean;
      };
      is_privileged: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      is_staff: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
      like_escape: {
        Args: {
          p: string;
        };
        Returns: string;
      };
      location_point: {
        Args: {
          p_region_id: number;
          p_district_id: number;
          p_settlement_id: number;
          p_mahalla_id: number;
        };
        Returns: {
          lat: number | null;
          lng: number | null;
        };
      };
      location_tier: {
        Args: {
          o_mahalla: number;
          o_settlement: number;
          o_district: number;
          o_region: number;
          o_has_location: boolean;
          t_mahalla: number;
          t_settlement: number;
          t_district: number;
          t_region: number;
          p_distance: number;
          p_radius: number;
          p_region_only: boolean;
        };
        Returns: number;
      };
      log_audit: {
        Args: {
          p_action: string;
          p_entity_type: string;
          p_entity_id: string;
          p_data?: Json | null;
          p_ip?: string | null;
        };
        Returns: undefined;
      };
      mark_payment_failed: {
        Args: {
          p_payment_id: string;
          p_status: Database["public"]["Enums"]["payment_status"];
        };
        Returns: undefined;
      };
      mark_payment_paid: {
        Args: {
          p_payment_id: string;
          p_provider_ref: string;
        };
        Returns: undefined;
      };
      match_candidates_for_vacancy: {
        Args: {
          p_vacancy_id: string;
          p_limit?: number | null;
        };
        Returns: {
          candidate_id: string | null;
          first_name: string | null;
          last_initial: string | null;
          avatar_url: string | null;
          headline: string | null;
          profession_id: number | null;
          profession_name: string | null;
          district_name: string | null;
          same_profession: boolean | null;
          same_category: boolean | null;
          distance_km: number | null;
          location_tier: number | null;
          experience_years: number | null;
          required_experience: number | null;
          availability: Database["public"]["Enums"]["availability_status"] | null;
          expected_salary_min: number | null;
          expected_salary_max: number | null;
          vacancy_salary_min: number | null;
          vacancy_salary_max: number | null;
          employment_match: boolean | null;
          rating_avg: number | null;
          rating_count: number | null;
          completeness: number | null;
          skills_matched: number | null;
          skills_required: number | null;
          has_transport: boolean | null;
          remote_ok: boolean | null;
          remote_allowed: boolean | null;
          phone_verified: boolean | null;
          identity_verified: boolean | null;
        }[];
      };
      match_vacancies_for_candidate: {
        Args: {
          p_limit?: number | null;
        };
        Returns: {
          vacancy_id: string | null;
          title: string | null;
          company_name: string | null;
          company_verified: boolean | null;
          district_name: string | null;
          same_profession: boolean | null;
          same_category: boolean | null;
          distance_km: number | null;
          location_tier: number | null;
          experience_years: number | null;
          required_experience: number | null;
          availability: Database["public"]["Enums"]["availability_status"] | null;
          expected_salary_min: number | null;
          expected_salary_max: number | null;
          vacancy_salary_min: number | null;
          vacancy_salary_max: number | null;
          salary_type: Database["public"]["Enums"]["salary_type"] | null;
          employment_type: Database["public"]["Enums"]["employment_type"] | null;
          employment_match: boolean | null;
          company_rating: number | null;
          completeness: number | null;
          skills_matched: number | null;
          skills_required: number | null;
          remote_allowed: boolean | null;
          remote_ok: boolean | null;
          urgent: boolean | null;
          published_at: string | null;
        }[];
      };
      payment_transition_allowed: {
        Args: {
          p_from: Database["public"]["Enums"]["payment_status"];
          p_to: Database["public"]["Enums"]["payment_status"];
        };
        Returns: boolean;
      };
      rate_limit_hit: {
        Args: {
          p_key: string;
          p_window_ms: number;
        };
        Returns: {
          hits: number | null;
          reset_at: string | null;
        }[];
      };
      rate_limits_cleanup: {
        Args: Record<PropertyKey, never>;
        Returns: number;
      };
      region_stats: {
        Args: Record<PropertyKey, never>;
        Returns: {
          id: number | null;
          slug: string | null;
          name_uz: string | null;
          vacancy_count: number | null;
          candidate_count: number | null;
        }[];
      };
      resolve_origin: {
        Args: {
          p_region_id: number;
          p_district_id: number;
          p_settlement_id: number;
          p_mahalla_id: number;
          p_lat: number;
          p_lng: number;
        };
        Returns: {
          region_id: number | null;
          district_id: number | null;
          settlement_id: number | null;
          mahalla_id: number | null;
          lat: number | null;
          lng: number | null;
          has_location: boolean | null;
          region_only: boolean | null;
        };
      };
      search_candidates: {
        Args: {
          p_query?: string | null;
          p_category_id?: number | null;
          p_profession_id?: number | null;
          p_region_id?: number | null;
          p_district_id?: number | null;
          p_settlement_id?: number | null;
          p_mahalla_id?: number | null;
          p_lat?: number | null;
          p_lng?: number | null;
          p_radius_km?: number | null;
          p_experience_min?: number | null;
          p_salary_max?: number | null;
          p_availability?: Database["public"]["Enums"]["availability_status"][] | null;
          p_employment_types?: Database["public"]["Enums"]["employment_type"][] | null;
          p_min_rating?: number | null;
          p_verified_only?: boolean | null;
          p_has_transport?: boolean | null;
          p_remote?: boolean | null;
          p_skill_ids?: number[] | null;
          p_sort?: string | null;
          p_limit?: number | null;
          p_offset?: number | null;
        };
        Returns: {
          id: string | null;
          first_name: string | null;
          last_initial: string | null;
          avatar_url: string | null;
          headline: string | null;
          profession_id: number | null;
          profession_name: string | null;
          experience_years: number | null;
          region_id: number | null;
          region_name: string | null;
          district_id: number | null;
          district_name: string | null;
          settlement_name: string | null;
          expected_salary_min: number | null;
          expected_salary_max: number | null;
          salary_type: Database["public"]["Enums"]["salary_type"] | null;
          availability: Database["public"]["Enums"]["availability_status"] | null;
          employment_types: Database["public"]["Enums"]["employment_type"][] | null;
          has_transport: boolean | null;
          remote_ok: boolean | null;
          rating_avg: number | null;
          rating_count: number | null;
          completed_jobs: number | null;
          phone_verified: boolean | null;
          identity_verified: boolean | null;
          certificate_verified: boolean | null;
          is_premium: boolean | null;
          completeness: number | null;
          skills: string[] | null;
          lat: number | null;
          lng: number | null;
          distance_km: number | null;
          location_tier: number | null;
          total_count: number | null;
        }[];
      };
      search_vacancies: {
        Args: {
          p_query?: string | null;
          p_category_id?: number | null;
          p_profession_id?: number | null;
          p_region_id?: number | null;
          p_district_id?: number | null;
          p_settlement_id?: number | null;
          p_mahalla_id?: number | null;
          p_lat?: number | null;
          p_lng?: number | null;
          p_radius_km?: number | null;
          p_employment_types?: Database["public"]["Enums"]["employment_type"][] | null;
          p_salary_min?: number | null;
          p_experience_max?: number | null;
          p_remote?: boolean | null;
          p_urgent?: boolean | null;
          p_transport?: boolean | null;
          p_accommodation?: boolean | null;
          p_company_id?: string | null;
          p_verified_only?: boolean | null;
          p_sort?: string | null;
          p_limit?: number | null;
          p_offset?: number | null;
        };
        Returns: {
          id: string | null;
          title: string | null;
          company_id: string | null;
          company_name: string | null;
          company_slug: string | null;
          company_logo: string | null;
          company_verified: boolean | null;
          profession_id: number | null;
          profession_name: string | null;
          salary_min: number | null;
          salary_max: number | null;
          salary_currency: string | null;
          salary_type: Database["public"]["Enums"]["salary_type"] | null;
          employment_type: Database["public"]["Enums"]["employment_type"] | null;
          work_schedule: Database["public"]["Enums"]["work_schedule"] | null;
          experience_min_years: number | null;
          region_id: number | null;
          region_name: string | null;
          district_id: number | null;
          district_name: string | null;
          settlement_name: string | null;
          lat: number | null;
          lng: number | null;
          remote_allowed: boolean | null;
          urgent: boolean | null;
          is_featured: boolean | null;
          is_promoted: boolean | null;
          transport_provided: boolean | null;
          accommodation_provided: boolean | null;
          meal_provided: boolean | null;
          published_at: string | null;
          distance_km: number | null;
          location_tier: number | null;
          total_count: number | null;
        }[];
      };
      start_conversation: {
        Args: {
          p_other_user: string;
          p_vacancy_id?: string | null;
          p_application_id?: string | null;
        };
        Returns: string;
      };
      talent_count: {
        Args: {
          p_profession_id: number;
          p_region_id?: number | null;
          p_district_id?: number | null;
          p_settlement_id?: number | null;
          p_radius_km?: number | null;
        };
        Returns: Json;
      };
      talent_summary: {
        Args: {
          p_region_id?: number | null;
          p_district_id?: number | null;
          p_limit?: number | null;
        };
        Returns: {
          profession_id: number | null;
          profession_slug: string | null;
          profession_name: string | null;
          candidate_count: number | null;
          vacancy_count: number | null;
        }[];
      };
      verification_level: {
        Args: {
          p_user_id: string;
        };
        Returns: number;
      };
    };
    Enums: {
      app_role: "job_seeker" | "employer" | "company" | "admin" | "moderator" | "super_admin" | "partner" | "recruiter";
      application_status: "applied" | "viewed" | "shortlisted" | "interview" | "offered" | "hired" | "rejected" | "withdrawn";
      availability_status: "immediately" | "within_week" | "within_month" | "open_to_offers" | "not_available";
      company_type: "individual" | "sole_proprietor" | "llc" | "farm" | "state" | "ngo" | "other";
      district_kind: "district" | "city";
      education_level: "none" | "secondary" | "vocational" | "bachelor" | "master" | "doctorate";
      employment_type: "full_time" | "part_time" | "temporary" | "freelance" | "daily" | "hourly" | "seasonal" | "internship" | "remote";
      message_kind: "text" | "image" | "document" | "system";
      notification_type: "new_application" | "application_status" | "new_matching_job" | "new_matching_candidate" | "new_message" | "interview" | "job_expiration" | "payment" | "subscription" | "verification" | "review" | "system";
      payment_status: "pending" | "paid" | "failed" | "refunded" | "cancelled";
      plan_audience: "employer" | "candidate";
      report_reason: "scam" | "spam" | "fake_job" | "illegal_job" | "misleading_salary" | "inappropriate" | "other";
      report_status: "open" | "reviewing" | "resolved" | "dismissed";
      report_target: "vacancy" | "user" | "company" | "message" | "review";
      request_status: "pending" | "approved" | "rejected";
      review_status: "published" | "hidden";
      salary_type: "monthly" | "daily" | "hourly" | "per_task" | "negotiable";
      settlement_kind: "city" | "town" | "village";
      subscription_status: "trialing" | "active" | "past_due" | "cancelled" | "expired";
      vacancy_status: "draft" | "pending_review" | "active" | "rejected" | "expired" | "closed";
      vacancy_tier: "standard" | "premium";
      verification_status: "unverified" | "pending" | "verified" | "rejected";
      verification_type: "phone" | "identity" | "certificate" | "company";
      work_schedule: "full_day" | "shift" | "flexible" | "night" | "weekends";
    };
    CompositeTypes: Record<string, never>;
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
export type FunctionReturns<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T]["Returns"];
