#!/usr/bin/env node
// Creates the local dev database and downloads PostgREST + Supabase Auth
// binaries (no Docker needed). Run: npm run stack:setup
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import pg from "pg";
import { authEnv } from "./setup-env.mjs";
import {
  ANON_KEY,
  AUTHENTICATOR_PASSWORD,
  BIN_DIR,
  DB_NAME,
  PG_ADMIN_URL,
  PORTS,
  ROOT,
  SERVICE_ROLE_KEY,
  SITE_URL,
  STACK_DIR,
  VERSIONS,
  dbUrl,
} from "./config.mjs";

const args = new Set(process.argv.slice(2));

function download(url, dest) {
  console.log(`↓ ${url}`);
  execFileSync("curl", ["-fsSL", "-o", dest, url], { stdio: "inherit" });
}

function ensureBinaries() {
  mkdirSync(BIN_DIR, { recursive: true });
  if (!existsSync(path.join(BIN_DIR, "postgrest"))) {
    const tar = path.join(STACK_DIR, "postgrest.tar.xz");
    download(
      `https://github.com/PostgREST/postgrest/releases/download/${VERSIONS.postgrest}/postgrest-${VERSIONS.postgrest}-linux-static-x64.tar.xz`,
      tar,
    );
    execFileSync("tar", ["xf", tar, "-C", BIN_DIR]);
  }
  if (!existsSync(path.join(BIN_DIR, "auth", "auth"))) {
    const tar = path.join(STACK_DIR, "auth.tar.gz");
    download(`https://github.com/supabase/auth/releases/download/${VERSIONS.auth}/auth-${VERSIONS.auth}-x86.tar.gz`, tar);
    mkdirSync(path.join(BIN_DIR, "auth"), { recursive: true });
    execFileSync("tar", ["xzf", tar, "-C", path.join(BIN_DIR, "auth")]);
  }
}

async function setupDatabase() {
  const admin = new pg.Client({ connectionString: PG_ADMIN_URL });
  await admin.connect();
  await admin.query(`drop database if exists ${DB_NAME} with (force)`);
  await admin.query(`create database ${DB_NAME}`);
  await admin.end();

  const db = new pg.Client({ connectionString: dbUrl() });
  await db.connect();
  const run = async (file) => {
    await db.query(readFileSync(path.join(ROOT, file), "utf8"));
    console.log(`✓ ${file}`);
  };
  await run("supabase/tests/shim/00_platform.sql");
  await db.query(`
    do $$ begin
      if not exists (select 1 from pg_roles where rolname = 'authenticator') then
        create role authenticator login noinherit password '${AUTHENTICATOR_PASSWORD}';
      else
        alter role authenticator with login password '${AUTHENTICATOR_PASSWORD}';
      end if;
    end $$;
    grant anon, authenticated, service_role to authenticator;
  `);

  await db.query("create schema if not exists auth");
  console.log("→ running Supabase Auth migrations");
  execFileSync(path.join(BIN_DIR, "auth", "auth"), ["migrate"], { env: authEnv(), stdio: "inherit" });
  await db.query(`
    grant usage on schema auth to anon, authenticated, service_role;
    grant execute on all functions in schema auth to anon, authenticated, service_role;
  `);

  for (const f of readdirSync(path.join(ROOT, "supabase/migrations"))
    .filter((f) => f.endsWith(".sql"))
    .sort()) {
    await run(`supabase/migrations/${f}`);
  }
  if (!args.has("--no-seed")) {
    for (const f of readdirSync(path.join(ROOT, "supabase/seed"))
      .filter((f) => f.endsWith(".sql"))
      .sort()) {
      await run(`supabase/seed/${f}`);
    }
  }
  await db.query("notify pgrst, 'reload schema'");
  await db.end();
}

ensureBinaries();
await setupDatabase();

const envFile = [
  "# Generated by scripts/local-stack/setup.mjs — LOCAL DEVELOPMENT ONLY",
  `NEXT_PUBLIC_SITE_URL=${SITE_URL}`,
  `NEXT_PUBLIC_SUPABASE_URL=http://localhost:${PORTS.gateway}`,
  `NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}`,
  `SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}`,
  "PAYMENT_PROVIDER=mock",
  "PAYMENTS_MOCK_ENABLED=true",
  "CRON_SECRET=local-dev-cron-secret",
  "",
].join("\n");
writeFileSync(path.join(STACK_DIR, "env.local"), envFile);
console.log(`\nLocal stack database ready. Environment written to .local-stack/env.local`);
if (!existsSync(path.join(ROOT, ".env.local"))) {
  console.log("Tip: cp .local-stack/env.local .env.local   (existing .env.local files are never overwritten)");
}
