-- Uzbekistan administrative hierarchy:
-- country -> region (viloyat) -> district/city (tuman/shahar) -> settlement (shahar/qishloq) -> mahalla
-- All data lives in the database (never hard-coded in the frontend) and is
-- managed by admins or imported from official datasets (SOATO codes).

create table public.countries (
  id integer generated by default as identity primary key,
  code text not null unique check (code ~ '^[A-Z]{2}$'),
  name_uz text not null,
  name_ru text,
  name_en text
);

create table public.regions (
  id integer generated by default as identity primary key,
  country_id integer not null references public.countries (id),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name_uz text not null,
  name_ru text,
  name_en text,
  soato_code text unique,
  lat double precision check (lat between -90 and 90),
  lng double precision check (lng between -180 and 180),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.districts (
  id integer generated by default as identity primary key,
  region_id integer not null references public.regions (id),
  slug text not null check (slug ~ '^[a-z0-9-]+$'),
  kind public.district_kind not null default 'district',
  name_uz text not null,
  name_ru text,
  name_en text,
  soato_code text unique,
  lat double precision check (lat between -90 and 90),
  lng double precision check (lng between -180 and 180),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (region_id, slug)
);

create table public.settlements (
  id integer generated by default as identity primary key,
  district_id integer not null references public.districts (id),
  slug text not null check (slug ~ '^[a-z0-9-]+$'),
  kind public.settlement_kind not null default 'village',
  name_uz text not null,
  name_ru text,
  name_en text,
  soato_code text unique,
  lat double precision check (lat between -90 and 90),
  lng double precision check (lng between -180 and 180),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (district_id, slug)
);

-- Mahallas always belong to a district; in villages they may also belong to a settlement.
create table public.mahallas (
  id integer generated by default as identity primary key,
  district_id integer not null references public.districts (id),
  settlement_id integer references public.settlements (id),
  slug text not null check (slug ~ '^[a-z0-9-]+$'),
  name_uz text not null,
  name_ru text,
  name_en text,
  code text unique,
  lat double precision check (lat between -90 and 90),
  lng double precision check (lng between -180 and 180),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (district_id, slug)
);

create index districts_region_idx on public.districts (region_id) where is_active;
create index settlements_district_idx on public.settlements (district_id) where is_active;
create index mahallas_district_idx on public.mahallas (district_id) where is_active;
create index mahallas_settlement_idx on public.mahallas (settlement_id) where is_active;
create index districts_name_trgm on public.districts using gin (name_uz extensions.gin_trgm_ops);
create index settlements_name_trgm on public.settlements using gin (name_uz extensions.gin_trgm_ops);

-- Mahalla settlement must be inside the same district.
create or replace function public.mahallas_check()
returns trigger
language plpgsql
as $$
begin
  if new.settlement_id is not null and not exists (
    select 1 from public.settlements s where s.id = new.settlement_id and s.district_id = new.district_id
  ) then
    raise exception 'MAHALLA_SETTLEMENT_MISMATCH' using errcode = '23514';
  end if;
  return new;
end;
$$;

create trigger mahallas_check before insert or update on public.mahallas
  for each row execute function public.mahallas_check();

-- ---------------------------------------------------------------------------
-- Location normalisation used by candidate_profiles, vacancies, companies.
-- Fills parent ids from the most specific level, validates consistency and
-- defaults coordinates to the most specific known centre point.
-- Expects columns: region_id, district_id, settlement_id, mahalla_id, lat, lng.
-- ---------------------------------------------------------------------------
create or replace function public.normalize_location()
returns trigger
language plpgsql
as $$
declare
  v_district integer;
  v_settlement integer;
  v_region integer;
  v_lat double precision;
  v_lng double precision;
begin
  -- On update, levels the caller did not touch are recomputed (parents) or
  -- dropped (stale children), and untouched coordinates are re-derived.
  if tg_op = 'UPDATE' and (
       new.region_id is distinct from old.region_id or new.district_id is distinct from old.district_id
       or new.settlement_id is distinct from old.settlement_id or new.mahalla_id is distinct from old.mahalla_id) then
    if new.region_id is not distinct from old.region_id then new.region_id := null; end if;
    if new.district_id is not distinct from old.district_id then new.district_id := null; end if;
    if new.settlement_id is not distinct from old.settlement_id then new.settlement_id := null; end if;
    if new.mahalla_id is not distinct from old.mahalla_id then new.mahalla_id := null; end if;
    if new.lat is not distinct from old.lat and new.lng is not distinct from old.lng then
      new.lat := null; new.lng := null;
    end if;
  end if;

  if new.mahalla_id is not null then
    select m.district_id, m.settlement_id, m.lat, m.lng
      into v_district, v_settlement, v_lat, v_lng
      from public.mahallas m where m.id = new.mahalla_id;
    if new.district_id is not null and new.district_id <> v_district then
      raise exception 'LOCATION_MISMATCH' using errcode = '23514';
    end if;
    new.district_id := v_district;
    if v_settlement is not null then
      if new.settlement_id is not null and new.settlement_id <> v_settlement then
        raise exception 'LOCATION_MISMATCH' using errcode = '23514';
      end if;
      new.settlement_id := v_settlement;
    end if;
    if new.lat is null and v_lat is not null then
      new.lat := v_lat; new.lng := v_lng;
    end if;
  end if;

  if new.settlement_id is not null then
    select s.district_id, s.lat, s.lng into v_district, v_lat, v_lng
      from public.settlements s where s.id = new.settlement_id;
    if new.district_id is not null and new.district_id <> v_district then
      raise exception 'LOCATION_MISMATCH' using errcode = '23514';
    end if;
    new.district_id := v_district;
    if new.lat is null and v_lat is not null then
      new.lat := v_lat; new.lng := v_lng;
    end if;
  end if;

  if new.district_id is not null then
    select d.region_id, d.lat, d.lng into v_region, v_lat, v_lng
      from public.districts d where d.id = new.district_id;
    if new.region_id is not null and new.region_id <> v_region then
      raise exception 'LOCATION_MISMATCH' using errcode = '23514';
    end if;
    new.region_id := v_region;
    if new.lat is null and v_lat is not null then
      new.lat := v_lat; new.lng := v_lng;
    end if;
  end if;

  if new.region_id is not null and new.lat is null then
    select r.lat, r.lng into v_lat, v_lng from public.regions r where r.id = new.region_id;
    new.lat := v_lat; new.lng := v_lng;
  end if;

  if (new.lat is null) <> (new.lng is null) then
    raise exception 'COORDINATES_INCOMPLETE' using errcode = '23514';
  end if;

  return new;
end;
$$;

-- Centre point of the most specific selected location.
create or replace function public.location_point(
  p_region_id integer, p_district_id integer, p_settlement_id integer, p_mahalla_id integer,
  out lat double precision, out lng double precision
)
language sql
stable
as $$
  select coalesce(m.lat, s.lat, d.lat, r.lat), coalesce(m.lng, s.lng, d.lng, r.lng)
  from (select 1) x
  left join public.mahallas m on m.id = p_mahalla_id
  left join public.settlements s on s.id = coalesce(p_settlement_id, m.settlement_id)
  left join public.districts d on d.id = coalesce(p_district_id, m.district_id, s.district_id)
  left join public.regions r on r.id = coalesce(p_region_id, d.region_id)
$$;

-- ---------------------------------------------------------------------------
-- RLS: public read of active rows, admin write.
-- ---------------------------------------------------------------------------
alter table public.countries enable row level security;
alter table public.regions enable row level security;
alter table public.districts enable row level security;
alter table public.settlements enable row level security;
alter table public.mahallas enable row level security;

create policy countries_read on public.countries for select using (true);
create policy countries_admin on public.countries for all using (public.is_admin()) with check (public.is_admin());

create policy regions_read on public.regions for select using (is_active or public.is_staff());
create policy regions_admin on public.regions for all using (public.is_admin()) with check (public.is_admin());

create policy districts_read on public.districts for select using (is_active or public.is_staff());
create policy districts_admin on public.districts for all using (public.is_admin()) with check (public.is_admin());

create policy settlements_read on public.settlements for select using (is_active or public.is_staff());
create policy settlements_admin on public.settlements for all using (public.is_admin()) with check (public.is_admin());

create policy mahallas_read on public.mahallas for select using (is_active or public.is_staff());
create policy mahallas_admin on public.mahallas for all using (public.is_admin()) with check (public.is_admin());
