-- Profession catalogue: category -> subcategory (categories.parent_id) -> profession -> skills

create table public.categories (
  id integer generated by default as identity primary key,
  parent_id integer references public.categories (id),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name_uz text not null,
  name_ru text,
  name_en text,
  icon text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  check (parent_id is null or parent_id <> id)
);

create table public.professions (
  id integer generated by default as identity primary key,
  category_id integer not null references public.categories (id),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name_uz text not null,
  name_ru text,
  name_en text,
  synonyms text[] not null default '{}',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.skills (
  id integer generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name_uz text not null,
  name_ru text,
  name_en text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.profession_skills (
  profession_id integer not null references public.professions (id) on delete cascade,
  skill_id integer not null references public.skills (id) on delete cascade,
  primary key (profession_id, skill_id)
);

create index categories_parent_idx on public.categories (parent_id);
create index professions_category_idx on public.professions (category_id) where is_active;
create index professions_name_trgm on public.professions using gin (name_uz extensions.gin_trgm_ops);
create index skills_name_trgm on public.skills using gin (name_uz extensions.gin_trgm_ops);

alter table public.categories enable row level security;
alter table public.professions enable row level security;
alter table public.skills enable row level security;
alter table public.profession_skills enable row level security;

create policy categories_read on public.categories for select using (is_active or public.is_staff());
create policy categories_admin on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy professions_read on public.professions for select using (is_active or public.is_staff());
create policy professions_admin on public.professions for all using (public.is_admin()) with check (public.is_admin());
create policy skills_read on public.skills for select using (is_active or public.is_staff());
create policy skills_admin on public.skills for all using (public.is_admin()) with check (public.is_admin());
create policy profession_skills_read on public.profession_skills for select using (true);
create policy profession_skills_admin on public.profession_skills for all using (public.is_admin()) with check (public.is_admin());
