-- Monetisation: plans, paid services, subscriptions and provider-independent payments.
-- Prices live in the database (admin managed). Card data is NEVER stored —
-- only the payment provider's reference/token.

create table public.subscription_plans (
  id integer generated by default as identity primary key,
  code text not null unique check (code ~ '^[A-Z_]+$'),
  audience public.plan_audience not null default 'employer',
  name_uz text not null,
  description_uz text,
  price_uzs bigint not null default 0 check (price_uzs >= 0),
  interval_months integer not null default 1 check (interval_months between 1 and 24),
  limits jsonb not null default '{}'::jsonb,
  features jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.paid_services (
  id integer generated by default as identity primary key,
  code text not null unique check (code ~ '^[a-z0-9_]+$'),
  audience public.plan_audience not null,
  name_uz text not null,
  description_uz text,
  price_uzs bigint not null check (price_uzs >= 0),
  duration_days integer not null default 7 check (duration_days between 1 and 365),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  company_id uuid references public.companies (id) on delete cascade,
  plan_id integer not null references public.subscription_plans (id),
  status public.subscription_status not null default 'active',
  current_period_start timestamptz not null default now(),
  current_period_end timestamptz not null,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index subscriptions_company_idx on public.subscriptions (company_id, status);
create index subscriptions_user_idx on public.subscriptions (user_id, status);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  amount_uzs bigint not null check (amount_uzs >= 0),
  currency text not null default 'UZS',
  status public.payment_status not null default 'pending',
  provider text not null check (provider ~ '^[a-z0-9_]+$'),
  provider_ref text,
  purpose text not null check (purpose in ('subscription', 'service')),
  plan_id integer references public.subscription_plans (id),
  service_id integer references public.paid_services (id),
  target_company_id uuid references public.companies (id) on delete set null,
  target_vacancy_id uuid references public.vacancies (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_ref),
  check ((purpose = 'subscription' and plan_id is not null) or (purpose = 'service' and service_id is not null))
);

create index payments_user_idx on public.payments (user_id, created_at desc);
create index payments_status_idx on public.payments (status, created_at desc);

create trigger subscriptions_updated_at before update on public.subscriptions
  for each row execute function public.set_updated_at();
create trigger payments_updated_at before update on public.payments
  for each row execute function public.set_updated_at();

-- Allowed payment state transitions (mirrored in src/features/payments/state.ts)
create or replace function public.payment_transition_allowed(p_from public.payment_status, p_to public.payment_status)
returns boolean
language sql
immutable
as $$
  select p_from = p_to
    or (p_from = 'pending' and p_to in ('paid', 'failed', 'cancelled'))
    or (p_from = 'paid' and p_to = 'refunded')
    or (p_from = 'failed' and p_to = 'pending')
$$;

create or replace function public.payments_guard()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'UPDATE' and not public.payment_transition_allowed(old.status, new.status) then
    raise exception 'INVALID_PAYMENT_TRANSITION' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger payments_guard before update on public.payments
  for each row execute function public.payments_guard();

-- Create a payment intent. The amount is always taken from the database price.
create or replace function public.create_payment_intent(
  p_purpose text,
  p_code text,
  p_provider text,
  p_company_id uuid default null,
  p_vacancy_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_plan public.subscription_plans;
  v_service public.paid_services;
  v_id uuid;
begin
  if auth.uid() is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = '28000';
  end if;
  if p_company_id is not null and not public.is_company_owner(p_company_id) then
    raise exception 'NOT_ALLOWED' using errcode = '42501';
  end if;
  if p_vacancy_id is not null and not exists (
    select 1 from public.vacancies v where v.id = p_vacancy_id and public.is_company_member(v.company_id)
  ) then
    raise exception 'NOT_ALLOWED' using errcode = '42501';
  end if;

  if p_purpose = 'subscription' then
    select * into v_plan from public.subscription_plans where code = p_code and is_active;
    if v_plan.id is null or v_plan.price_uzs = 0 then
      raise exception 'PLAN_NOT_FOUND' using errcode = 'P0001';
    end if;
    if v_plan.audience = 'employer' and p_company_id is null then
      raise exception 'COMPANY_REQUIRED' using errcode = 'P0001';
    end if;
    insert into public.payments (user_id, amount_uzs, provider, purpose, plan_id, target_company_id)
    values (auth.uid(), v_plan.price_uzs, p_provider, 'subscription', v_plan.id, p_company_id)
    returning id into v_id;
  elsif p_purpose = 'service' then
    select * into v_service from public.paid_services where code = p_code and is_active;
    if v_service.id is null then
      raise exception 'SERVICE_NOT_FOUND' using errcode = 'P0001';
    end if;
    if v_service.code like 'vacancy_%' and p_vacancy_id is null then
      raise exception 'VACANCY_REQUIRED' using errcode = 'P0001';
    end if;
    if v_service.code = 'featured_employer' and p_company_id is null then
      raise exception 'COMPANY_REQUIRED' using errcode = 'P0001';
    end if;
    insert into public.payments (user_id, amount_uzs, provider, purpose, service_id, target_company_id, target_vacancy_id)
    values (auth.uid(), v_service.price_uzs, p_provider, 'service', v_service.id, p_company_id, p_vacancy_id)
    returning id into v_id;
  else
    raise exception 'INVALID_PURPOSE' using errcode = 'P0001';
  end if;
  return v_id;
end;
$$;

-- Called ONLY by the backend (payment webhook / provider callback) after the
-- provider confirmed the payment. Activates the purchased entitlement.
create or replace function public.mark_payment_paid(p_payment_id uuid, p_provider_ref text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_payment public.payments;
  v_plan public.subscription_plans;
  v_service public.paid_services;
  v_start timestamptz;
begin
  select * into v_payment from public.payments where id = p_payment_id for update;
  if v_payment.id is null then
    raise exception 'PAYMENT_NOT_FOUND' using errcode = 'P0001';
  end if;
  if v_payment.status = 'paid' then
    return; -- idempotent
  end if;

  update public.payments set status = 'paid', provider_ref = coalesce(p_provider_ref, provider_ref), paid_at = now()
  where id = p_payment_id;

  if v_payment.purpose = 'subscription' then
    select * into v_plan from public.subscription_plans where id = v_payment.plan_id;
    select greatest(now(), coalesce(max(current_period_end), now())) into v_start
    from public.subscriptions
    where user_id = v_payment.user_id and company_id is not distinct from v_payment.target_company_id
      and plan_id = v_plan.id and status = 'active';
    insert into public.subscriptions (user_id, company_id, plan_id, status, current_period_start, current_period_end)
    values (v_payment.user_id, v_payment.target_company_id, v_plan.id, 'active', v_start,
            v_start + make_interval(months => v_plan.interval_months));
  else
    select * into v_service from public.paid_services where id = v_payment.service_id;
    if v_service.code = 'vacancy_promotion' then
      update public.vacancies set promoted_until = greatest(coalesce(promoted_until, now()), now()) + make_interval(days => v_service.duration_days)
      where id = v_payment.target_vacancy_id;
    elsif v_service.code = 'vacancy_premium' then
      update public.vacancies set vacancy_tier = 'premium', is_featured = true,
        promoted_until = greatest(coalesce(promoted_until, now()), now()) + make_interval(days => v_service.duration_days)
      where id = v_payment.target_vacancy_id;
    elsif v_service.code = 'candidate_premium' then
      update public.candidate_profiles set premium_until = greatest(coalesce(premium_until, now()), now()) + make_interval(days => v_service.duration_days)
      where id = v_payment.user_id;
    elsif v_service.code = 'featured_employer' then
      update public.companies set is_featured = true,
        featured_until = greatest(coalesce(featured_until, now()), now()) + make_interval(days => v_service.duration_days)
      where id = v_payment.target_company_id;
    end if;
  end if;

  perform public.create_notification(v_payment.user_id, 'payment', 'Toʻlov qabul qilindi',
    v_payment.amount_uzs || ' soʻm', '/dashboard/billing', jsonb_build_object('payment_id', v_payment.id));
end;
$$;

create or replace function public.mark_payment_failed(p_payment_id uuid, p_status public.payment_status)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_status not in ('failed', 'cancelled', 'refunded') then
    raise exception 'INVALID_STATUS' using errcode = 'P0001';
  end if;
  update public.payments set status = p_status where id = p_payment_id;
end;
$$;

revoke execute on function public.mark_payment_paid(uuid, text) from public, anon, authenticated;
revoke execute on function public.mark_payment_failed(uuid, public.payment_status) from public, anon, authenticated;
grant execute on function public.mark_payment_paid(uuid, text) to service_role;
grant execute on function public.mark_payment_failed(uuid, public.payment_status) to service_role;

alter table public.subscription_plans enable row level security;
alter table public.paid_services enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payments enable row level security;

create policy plans_read on public.subscription_plans for select using (is_active or public.is_admin());
create policy plans_admin on public.subscription_plans for all using (public.is_admin()) with check (public.is_admin());
create policy services_read on public.paid_services for select using (is_active or public.is_admin());
create policy services_admin on public.paid_services for all using (public.is_admin()) with check (public.is_admin());

create policy subscriptions_read on public.subscriptions for select
  using (user_id = auth.uid() or (company_id is not null and public.is_company_member(company_id)) or public.is_admin());
create policy payments_read on public.payments for select using (user_id = auth.uid() or public.is_admin());
-- No insert/update policies: payments are created via create_payment_intent()
-- and settled by the backend with the service role.
